### ISSUE TITLE
Feature request for multiple quaternion slerp

### ISSUE THREAD

**Issue by git-dhruv** [naver/roma#15]
Hi,

I was transferring my code from scipy's rotation to roma for batched operations. Below is my scipy code:

```
from scipy.spatial.transform import Rotation as Rot, Slerp as Slerp

# Random quaternions
init_rot = Rot.from_euler('xyz', [0, 0, 0])
rot_a = Rot.from_euler('xyz', [0, 0, 3.14/2])
rot_b = Rot.from_euler('xyz', [0, 0, 3.14 + 1e-2])
final_rot = Rot.from_euler('xyz', [0, 0, 0])
# Timestamps and query times
timestamps = [0, 0.5, 1, 1.5]
query_times = [0, 0.2, 0.5, 1, 1.25, 1.5]

## Specifically this part ##
packed_rots = Rot.concatenate((init_rot, rot_a, rot_b, final_rot))
slerp_interp = Slerp(timestamps, packed_rots)
interp_rots = slerp_interp(query_times).as_euler('xyz', degrees=True).round()
print(interp_rots)

```

The example in the documentation can interpolate between 2 quaternions. Any chance roma's Slerp can handle using the same instance for multiple quaternions? Would love to hear any alternative approach as well.

**Comment by rbregier** [comment]
Hi,
Our Slerp implementation is designed for interpolation between two rotations.
One could implement interpolation along a trajectory composed of multiple rotations by selecting the appropriate pair of successive rotations based on timestamps using Pytorch methods like https://pytorch.org/docs/stable/generated/torch.searchsorted.html

This is a rather specific use case, but I will try to consider it for the next releases.

**Comment by git-dhruv** [comment]
Hi, thanks for the response. 
I implemented my own using torch's searchsorted. If you are interested, I can raise a PR after cleaning up the code.

**Comment by rbregier** [comment]
Hi, I am glad you could make it work for your application.
What refrains me to implement this in the library for now (besides time) is that I am not quite sure about how it should be done: given a batch of  AxT input rotations associated with AxT timestamps, and a batch of B query timesteps, which output are we expecting?
- if we assume A==B, or B==1, we might want to get A rotations corresponding to querying each sequence of rotations with a given timestep.
- we might also want AxB outputs, querying each sequence of rotations with the B timesteps provided.
- If A and B contain multiple dimensions, we could also want something in-between.

Additionally:
- Multiple extrapolation behaviors could be considered (i.e. clamping to the closest rotation, or extrapolation).
- Supporting timestamp-based interpolation for rotations only would make little sense and one would probably have to implement it for translations as well.

Integration into RoMa would require a clean API covering the different cases. Otherwise I think it would be best to let the user implement the behavior he/she is interested in.
