### ISSUE TITLE
Will Euler Angles be supported?

### ISSUE THREAD

**Issue by jasam-sheja** [naver/roma#16]
Thank you for your hard work.
This library is a strong alternative to `scipy.sptial.transformation.Rotation`.
However, it's missing Euler angles. 
I believe supporting Euler angles will improve the reach of this library.

Minimal addition the API could look like this:
```python
def euler_to_unitquat(R, convention):
    ...
def unitquat_to_euler(R, convention):
    ...
```

**Comment by rbregier** [comment]
Hi, thank you the comment.
I initially excluded Euler angles as they tend to be a source of bugs, corner cases, and complications due to the many conventions to support.
Yet I understand that some users might like them, for example to interface with existing code.
I will have a look into that for the next release.

**Comment by rbregier** [comment]
Hi,
I added support for Euler angles in the latest version of the repo.
Would you mind testing it and providing some feedback before I update the doc and PyPi package?
```
pip install git+https://github.com/naver/roma
```

**Comment by rbregier** [comment]
Thanks a lot for the feedback.

Regarding 1., I chose the input list approach  because of its flexibility: it allows using raw float values like `euler_to_unitquat('xyz', [0.3, 0.4, 5.0])` as input as well as list of tensors.
I will see if I can handle inputs differently depending on whether they are lists or tensors.

Regarding 2., I am a bit reluctant for multiple reasons:
- the "natural" way of inverting is actually trivial but involves a convention change: the inverse of 'xyz' Euler angles (alpha, beta, gamma) are 'zyx' angles (-gamma, -beta, -alpha). This is probably not what the end user is looking for.
- composition can already be performed using the proposed API: `euler_to_unitquat(convention1 + convention2, angles1 + angles2) ` (assuming list inputs).
- Most importantly, users with limited background might be tempted to use Euler angles as base representation if these functions were available. In most cases, I think this is a bad idea and I would not want to encourage this.

**Comment by rbregier** [comment]
euler_to_xxx now supports tensors as input and I added an optional `as_tensor` argument to xxx_to_euler:
https://naver.github.io/roma/index.html?highlight=euler#roma.euler.unitquat_to_euler
